### ISSUE TITLE
Please stay safe out there.

### ISSUE THREAD

**Issue by db626** [FACG5/Twig#106]
We're getting news about Gaza here. I hesitate to write a rather stupid thing like 'stay safe out there' (like how does one accomplish that), but you know... stay safe out there. Work comes after your safety. Thanks for all your work, thanks for being part of the Twig family. We worry about you.

**Comment by FarahZaqout** [comment]
Thank you for your concern and kind words, Bradley. Thankfully everyone is fine and the situation has cooled down. 

We're back at GSG, and work is in progress.
