### ISSUE TITLE
Oh dear, what to do if a doctor can speak a language but not write it...

### ISSUE THREAD

**Issue by db626** [FACG5/Twig#132]
Dear Group,

I don't know if you've ever heard of ListServs, but they're pretty much old-school groups that share an interest- you subscribe to a group but can't see anyone else who's in it- you can write an email to the listserv address which will in turn email everyone in the group without you seeing who they are. Since there's no 'medical translation' group, I'm basically SPAMing people. Anyway the most recent email I wrote was to a group of 2200 medical educators. Two of them must have passed on my information to students, because I've got a about 6 messages either from Mississippi or Florida. In total I've probably got about 20 people so far who have said they'll test our system.

Offhand I'd say we've got 2 Spanish speakers, 2 Arabic speakers, an African doctor from the Congo (he speaks 5 languages), 2 people from India and a Brazilian. The good news is that many of these people are doctors.

IDEA:

Is there a way to note which of these people have emails that come from an institutional email address... for example an .edu email address in the States stands for 'education', it's a good marker that whoever is writing to you is a real student.

PROBLEMS:

1) The Indian student mentions that she speaks three languages, including Hindi, but she can't write in Hindi. So.... is there a way to have volunteers use a tickbox that says if they can write in the languages they list. I know many Russians for example who can't write using Cyrillic etc. 

My gut instinct is to say that if people are doing volunteer audio translations, they MUST provide us with an audio translation (for example in Spanish), written translation (in Spanish), and they must tell us if they've changed the question and provide us with a written English translation if they've changed the question in any way. (That's 3 steps to an audio translation)

My other gut instinct is that if you can't write in a language, you should ONLY be able to verify in that language and not translate. 

NEXT PROBLEM: 

Verification: I've got people that are telling me that they speak Cuban Spanish or Brazilian Portugese or Egyptian Arabic. 

How about we let anyone who speaks Arabic verify other Arabic translations, BUT we ask them if they feel comfortable doing it.

For example we've had users sort their language into language/dialect (group/subgroup)... So if someone speaks Arabic, we open up all Arabic translations for them to verify, but if their dialect is different they see a popup, something like:

Your language is: Arabic
Your dialect is: Tunisian Spoken

We have a translation ready for you in:

Language: Arabic
Dialect: Najdi Spoken

Do you believe you can verify this language/dialect? 
(If you are in doubt, select 'no')

____ Yes
____ No

**Comment by FarahZaqout** [comment]
Hey!

There is a very simple way to verify the last few characters of email address. It won't be a problem.
As for being able to verify but not translate, that's also doable.

Would you be available for a video discussion this week with the rest of the team?
I feel that if we can discuss these ideas and reflect on the development of the app in general, it would ensure that we provide the best quality possible.

What do you think?

**Comment by db626** [comment]
Sure, what day works best for you?

**Comment by FarahZaqout** [comment]
The sooner the better. We are available Sunday to Thursday as a team. Any of these days works, between 8AM and 4PM in order for everyone to be present.

It comes down to which day suits you best.

**Comment by db626** [comment]
Tomorrow at 3?

**Comment by db626** [comment]
Or tomorrow at 2? I’ve forgot about the time difference

**Comment by FarahZaqout** [comment]
I had forgotten that tomorrow is supposed to be a national holiday. However, if the office is open I will let you know. It is suitable for us in that case.

If it's not open, we can do it after tomorrow.

**Comment by db626** [comment]
Sure. Any day late afternoon

**Comment by FarahZaqout** [comment]
Alright. Tomorrow the office is open so we can hold the meeting. Is it London or Jerusalem time though?

**Comment by db626** [comment]
London time, late afternoon. You tell me when.

**Comment by FarahZaqout** [comment]
There's two hours difference, so I'm wondering if 1pm is okay with you?

**Comment by db626** [comment]
Ok!

**Comment by db626** [comment]
If I haven't already confirmed, see you at 1 tomorrow.
