### ISSUE TITLE
Sign Up form

### ISSUE THREAD

**Issue by lubnaabd** [FACG5/Twig#14]
#### Registration process should consist of two steps:
**- Step 1:**
- [x] register by email:
     * first name
     * last name
     * email
     * password
- [x] register via linkedIn. 

**- Step 2:**
 - [x] enter language
 - [x] enter dialect
 - [x] specify English proficiency.  

Relates #5

**Comment by FarahZaqout** [comment]
Please document your progress in the issue body and when your pull request is ready, check the boxes that are completed by the pull request.
