### ISSUE TITLE
Protect the routes if not login

### ISSUE THREAD

**Issue by HemaSAli** [FACG5/Twig#140]
### Protect the routes before login
protecting the pages and api routes which user can't see it if he isn't login, the only page which user can see if he isn't login is Home page.
the protection will be in front-end and back-end which contain middle-ware which will check the authentication

**Comment by Aditya-Kolla** [comment]
Can I work on this?

**Comment by HemaSAli** [comment]
how did you find this project ?
@Aditya-Kolla

**Comment by FarahZaqout** [comment]
Hello, @Aditya-Kolla This project is part of a pre-planned full-stack course with the Gaza Sky Geeks and Founders and Coders and is not an open project. I regret to let you know that we cannot allow non-students to work on the project.

Thank you for the offer.

**Comment by Aditya-Kolla** [comment]
Oh, it's alright. Work hard :)
