### ISSUE TITLE
Notes for tomorrow's meeting, I almost forgot

### ISSUE THREAD

**Issue by db626** [FACG5/Twig#156]
I almost forgot to ask, how have we figured out to 'reward' volunteer translators? Badges? ...If so, I think we should have a special badge for the first test-users, plus maybe a different one for the first 100-200 users once we 'open for business'. I'm noticing that many of these medical students are coming from similar medical schools, word must be being passed around within faculties. I think it would be nice if they got recognized, as through word of mouth they might encourage more students. ...I've discovered it's REALLY difficult to contact med students directly.

**Comment by FarahZaqout** [comment]
Aha, we will discuss this today, and perhaps come up with some figma design later on.
