### ISSUE TITLE
"Specializations", which we are now calling "Translation Categories"

### ISSUE THREAD

**Issue by db626** [FACG5/Twig#172]
Remember the 'mission control' page we looked at today? I'm attaching it here.
As I said in previous feedback, I'd like this page to be a hub of what the user can do with the site:

TRANSLATE
VERIFY
ADD QUESTIONS
DISCUSSION FORUMS
(+ badges)

Ok. Let's imagine the user clicks 'translate", and it takes them to what we used to call 'specializations'. We're now calling them 'translation categories'.

We don't have a ton of time to re-invent the wheel, so I'm asking Farah: does anyone in the group have an iphone, or do you all use android? If you have an iphone you can download an app called Medibabble (it would be our competition, except it's lame. But they do have the 'categories' thing done really well:

[http://medibabble.com/](url)

http://medibabble.com/

I'm sending you some screenshots from my medibabble. The only problem is, once you click on each thing, it brings up subcategories. Like, if you click on "Chief Complaint", it will bring up subgroups. It would be very difficult for me to screenshot the whole app, easier if you could download the app and take the translation categories from there.

WHAT THE TRANSLATION CATEGORIES PAGE NEEDS:

-At the top you must put a link to Twig's pdf guidance on how to translate.
(for our test users it won't matter because I can just give it to them, but it is in our Dropbox file)
-You must put the sentence:
"Twig is not intended to try and gain informed consent from patients. It is not intended to explain medical procedures and/or their risks. Twig is not intended to explain how to administer or take medicine and/or possible side effects of medication.
-Steal the category system from MediBabble if you can.
- Add the following categories:
   + Physical Therapy
   + Dental
   + Psychological
   + Safeguarding
      (examples: human trafficking, abuse, etc)
   + Radiology Tech
   + Midwifery

Clearly I may need to go to the old pdf of 450 medical questions and fit them into the Medibabble categories. I'll look at that tomorrow. We may be able to give test users a smaller pool of questions to answer than 450.
       
[MediBabble1.pdf](https://github.com/FACG5/Twig/files/2601304/MediBabble1.pdf)
[MediBabble2.pdf](https://github.com/FACG5/Twig/files/2601305/MediBabble2.pdf)

[MissionControl.pdf](https://github.com/FACG5/Twig/files/2601267/MissionControl.pdf)

**Comment by FarahZaqout** [comment]
@ali-7 take a look.
