### ISSUE TITLE
Testing Issues...

### ISSUE THREAD

**Issue by db626** [FACG5/Twig#210]
I've sent a copy of this message to Max, because he's sent me some guidance on user testing. I just want to be clear on testing. Sorry it's taken me to the weekend to get back to you about specifically. I've finally got the time to read what you wrote to me thoroughly regarding testing.

As you may know I've been canvassing it seems the entire world to get test users- of course mine have to be bilingual medical professionals so the job isn't easy. I've got about 30 people signed up to do it so far (no doubt some will drop out, as is always the case).

I just want you to be aware of the following:

1) I will not be able to be with them physically while they test, they're med students principally located in Central Lancashire (UK), Mississippi (US), Durban (South Africa), and Florida (US). I'll have to get email feedback from them.

2) Because users are supposed to complete specific tasks, and the principal thing that users can do is translate then verify the translations of others- should I be planning *two* testing days? Certainly everyone would have to provide a translation on day 1 on order for verifiers to have anything to translate.

3) Provided there are two testing days, when should I plan them? They are ready anytime.

4. The principal tasks, it seems to me that users can complete, are 1) registration, 2) translating questions, 3) verifying the translations of others, 4) adding questions within the system.  ...what would my team like me to test- will all four tasks be up and running? Need team input.

Let me know,

Bradley.

P.S. We've got a recent volunteer that speaks a language called Luganda. If you have time please add it, if not ok.

**Comment by db626** [comment]
Farah & Team:

SUPERRRRR!! Thank you very much. I'll let all of the volunteers to know to be ready Wednesday and Thursday.

On Wednesday I'll have them do two tasks: register and translate,
On Thursday I'll have them verify and add.

Farah, the next question I have is very important, which is why I included Max in the last email. I want to be sure that the testing is done properly. Certainly you must give grades to your own programmers on the 'success' of the platform, which comes down to testing. Founders and Coders has stressed, in our meetings, the idea of testability.

Do you feel that the number of volunteers we have is typical of other product owners? Do you feel that an email survey is sufficient to test as I can't be with them in actual person?

Will these volunteers need to test the final system once it's done?

Please let me know if I can do anything to help or improve testing.

B

**Comment by maxgerber** [comment]
Hi @FarahZaqout & @db626,

In my experience, it is always ideal to walk people through a user testing session with some kind of script. Apart from anything else this helps to **standardise the experience** for the testers and minimise factors which might affect the reliability of the test.  

So, how about, for Wednesday and Thursday, we combine forces and come up with a joint user testing script? We could then [**conduct user testing remotely using Google Hangouts**](https://www.weareconvoy.com/2016/01/using-google-hangouts-on-air-for-remote-usability-testing/), with @db626 asking the questions, and the rest of the team observing.

I think this could be a really good learning experience for all of us, considering our geographical constraints, to learn how to conduct these sessions.

Let me know your thoughts!

Max

**Comment by db626** [comment]
Hi Max & Farah.

I'm confused. I agree we need a script, but are we still going with in-person user testing?

For the people that live in the UK this might be feasible given that there's no time difference in the UK, but there are test users in Africa and the States as well. The States is 5-7 hours 'behind', and so 5pm London time is when America is waking up. That would mean not sleeping for me for two nights, so I'd go to sleep Tuesday night, then get my next full night's sleep Friday night, given that we're doing two day's testing.

Also, these people are med students, and I'm sure they're busy. As such I'd imagine there'd be quite a bit of people dropping out of testing if I can't fit into their schedules.

We've currently got a list of 40 volunteers, and I imagine some will drop. If we're committed to doing in-person testing I can imagine maybe doing that over two days with a few test users, but certainly not 30-40.

An email survey will get us more people's feedback. An in-person survey will get us more quality feedback.

Another option is that I could offer to be available on Google Hangouts for people who want to test in-person, and give the rest of them an email survey (hybrid model).

Testing is important, let me know.

It is important for me to say that these aren't 'test' users to me... they're also Twig's first members. I estimate that I've contacted 3,000 individuals at universities, professional bodies and other educational institutions to get these 40 volunteers... I need to give people that can't test in-person something to do so they can feel useful, because I'm hoping they sign up to translate later.

**Comment by maxgerber** [comment]
Hi Bradley,

Remote testing is a little bit "in-person" in that it happens live, but it means that we're all in our separate locations, and interacting with each other using a google hangouts call/video conference. The user shares their screen whilst we go through our script and give them tasks to complete. The user thinks out loud, and we write down their responses, giving them prompter questions if needed. I hope that makes sense?

I agree, time zones are definitely an issue! I think your idea of a hybrid model is a good solution, and a nice way to engage people early on in Twig! Luckily, in usability testing, [**the magic number is 5**](https://www.nngroup.com/articles/how-many-test-users/), which should help make your task of finding people a little easier.

**Comment by db626** [comment]
Sounds great, it's good to have a solid number- I can probably reach the magic number of 5.

Will the test users be using the URL that's here on github, or will you be giving me a new URL? (and login details that the group has given me).

I'll offer test users in Britain the opportunity to test live. I'e got your script, I'd be happy to have the team help me write a script- in reality two scripts (because we've got two days of testing)- but I'd have to see you all tomorrow at 1 or 2 in the afternoon my time to do it...

Let me know. If I we don't get the opportunity to meet up together I'll use the materials you gave me to create a script.

B

**Comment by maxgerber** [comment]
awesome. @FarahZaqout over to you 😉

**Comment by db626** [comment]
Wait one second, Max!

Just one last note: Max it's unclear to me how I'll do live testing using my microphone and camera (Hangouts or Skype), if our users will need to use their microphones and possibly video to record translations...

**Comment by db626** [comment]
Wait one second, Max!

Just one last note: Max it's unclear to me how I'll do live testing using
my microphone and camera (Hangouts or Skype), if our users will need to use
their microphones and possibly video to record translations... is this a
deal breaker for live testing?

**Comment by maxgerber** [comment]
Hi @db626,
Good question. I just tried this out by using a [dummy video recording site](https://www.webrtc-experiment.com/RecordRTC/) whilst screensharing with a colleague on Google Hangouts, and it seemed to work fine. I think the underlying technology can be used in multiple places.

**Comment by db626** [comment]
Thx!

**Comment by FarahZaqout** [comment]
Hey, sorry for the late response.

@db626 We will be using the same link (twig-project.herokuapp). As for the login, people will be able to sign up and login with whatever credential they like.

**Comment by db626** [comment]
No worries. Do we have a meeting tomorrow to come up with interview
questions for the test users, or are you happy to leave me to do it? If you
want to meet I can do it at 1 or 2 in the afternoon, London time.

B

**Comment by db626** [comment]
Ok Farah, but at what time?

**Comment by db626** [comment]
I’m running 10 mins late
