### ISSUE TITLE
Updated volunteer list, 10 new translators, new issue.

### ISSUE THREAD

**Issue by db626** [FACG5/Twig#237]
[VolunteerTranslators3 Sheet1.pdf](https://github.com/FACG5/Twig/files/2613127/VolunteerTranslators3.Sheet1.pdf)

Hello group. Here's an updated list of the volunteers for this week. If you've already completed the language part don't worry about the new languages. I just thought you'd want to see it. I don't know how many volunteers count as a 'successful' number for you.

New issue (not for you, just for me): Ethnologue was supposed to be the world's most complete list of the world's languages and dialects. However, a new volunteer has mentioned Luganda, which is not listed on Ethnologue as far as I can see. It is listed on a wiki page for Uganda. This prompts me to ask the question of whether in the distant future I'll have to add more languages to our list- whether we'd get closer to 8,000 rather than 7,000. Just a point. This is my problem not yours at the moment.

**Comment by FarahZaqout** [comment]
Well, first that comes to mind is to have the Enthologue list as the base on which we can expand. 

A request for adding new language to the database can be introduced as a feature available to users, and the admin (you) can verify that the language does exist.

I will be honest however, I don't think we will be able to get down to this one. I'm just throwing in my two cents.

**Comment by db626** [comment]
Agreed that we probably won't have time to get to adding languages.

Farah, can I ask:

In the original packet I gave you, I asked a lot about just 'plonking' third-party software in to do some of the things Twig needed to; specifically:

- record audio
- record video
- user forums
- identity verification

Have you used third-party software for any of this? Will Twig be able to record video by this week for our American Sign Language volunteer?

I'm asking because I know from previous research that third-party software may provide software updates without us, but if we reinvent the wheel it will be up to Twig to raise the funding to update these fundamental parts of our platform as time moves on.

Please let me know if we're coming up with our own solutions on these fronts, or if we're using someone else.

I am hoping to be especially hands-on this week because I'd prefer that we have a stress-free ending phase without surprises (if possible).

**Comment by FarahZaqout** [comment]
For now we are using a module that allows people to upload files to the Twig server itself, so audio and video records are uploaded by the users to the Twig website.

There is an API (kinda software) developed by google that is stable and reliable for recording media. It allows recording directly from the browser using the user's camera after permission is granted.
