### ISSUE TITLE
[Fix] using componentWillRecieveProps when adding question

### ISSUE THREAD

**Issue by HemaSAli** [FACG5/Twig#330]
#### Using componentWillRecieveProps when adding question
when adding question we send a new props to question Card component, so we need to run the function componentWillRecieveProps(props), to set the new props in the state
the new props which contain the new values of questions

**Comment by FarahZaqout** [comment]
```componentWillReceiveProps``` will be deprecated in the next React version. This means it can lead to breaking changes or unexpected problems. [Check out this article](https://hackernoon.com/replacing-componentwillreceiveprops-with-getderivedstatefromprops-c3956f7ce607).

```getDerivedStateFromProps``` Is the one to be safely used. 

I need to read up more on them. [This is a useful (but a bit confusing) github discussion.](https://github.com/reactjs/reactjs.org/issues/721)
