### ISSUE TITLE
[Refactor] statistic in the homepage 

### ISSUE THREAD

**Issue by ali-7** [FACG5/Twig#339]
Refactor statistic component in the homepage after getting data from backend

**Comment by FarahZaqout** [comment]
@ali-7 Wait, did we not agree to rewrite the homepage? I'm a little confused.

**Comment by ali-7** [comment]
@FarahZaqout do you want to remove the statistic form it ?

**Comment by ali-7** [comment]
@FarahZaqout i refactored all the homepage on branch, but i did't open a pr for it until we revisited together tomorrow .
