### ISSUE TITLE
Say Hello to Bradley

### ISSUE THREAD

**Issue by FarahZaqout** [FACG5/Twig#72]
Hello, @lubnaabd @ali-7 @HemaSAli.

Bradley has joined the repository. Say Hi to her.

**Comment by db626** [comment]
Bradley says hello too. I've heard GitHub is supposed to be life-changing, we'll see...

**Comment by HemaSAli** [comment]
Hi @db626, nice to meet you here :smile: 
I hope you have a good time with us :heart:

**Comment by ali-7** [comment]
Hi Bradley, welcome to our little shop :smiley: .
