### ISSUE TITLE
Update: Where I am

### ISSUE THREAD

**Issue by db626** [FACG5/Twig#73]
Hello Group!

Farah was nice enough to show me how GitHub works this morning... I thought I'd let you know what I've been up to since our original meeting.

I've:
-drafted a very long user agreement for users to use
(needs to be completed with working web addresses but otherwise done)
-been working on a privacy policy
-been working on a tutorial of how to do a successful translation
(powerpoint that will be transferred to video)
-drafted some FAQs
-contacted about 3 professors or academics per night to see if they've got students that would be willing to volunteer to test the system.
-made a flyer for people to put up in their hospitals, etc.

Feedback:

Either nothing at all or very positive. Have got 3-4 translators that are willing to volunteer already. One who speaks Arabic (very good as it's a useful language for us). Another that teaches medical English in Durban, South Africa who will be passing on our information to several doctors in inth DRC/Chile (useful).

I'm up to about 5,500 contacts on LinkedIn, most medical professionals. I'll put a call out on my LinkedIn wall as we get closer, but am trying not to count on this.

Thoughts:

I can't remember whether it was Yasmin who asked, but someone asked 'what does success look like?' ...My answer at the time was getting one language in the system, which essentially would prove that crowdsourced medical translation was possible (which makes it easier if I've got to ask foundations for funding in future). Because I don't have a lot of control over who volunteers and what language they speak, perhaps it would be good to gauge how long volunteer translators stay on the site as a measure of success? That we can ccontrol. Of course I don't know what a 'long time' or very little time would be.

Last thought: what do you think about putting a link for patients to put their stories up (good or bad)? I am genuinely asking, I don't know the answer. The patients wouldn't be able to use their doctors' names or hospital names, but since we don't really know what happens behind closed doors it might be useful. I'm thinking more from a funding perspective, too. Like, in future if I don't have a ton of translations but I do have a ton of horrendous patient stories it might be easier to get funding. 

This was all borne out of Ali's original thoughts about being sure everyone who logs in is a doctor... the solution was to make Twig a 'big tent' where everyone is welcome. Why not welcome patients too?

Of course this goes to having a forum, and as I said before if there's no plugin to do this (forums) don't reinvent the wheel. Perhaps we can just fix the forum problem by linking to some outside Reddit link or something.

If we're talking about things we can control, making a cozy system where people want to stay for a long time is success. Otherwise, whatever gets me funding to open up the system. All this of course provided we've got something free of bugs too, that goes without saying. 

THANK YOU for your hard work!!!

Bradley

**Comment by FarahZaqout** [comment]
Great. I'm glad to know you're generating momentum.

As for the patients being able to put their stories up, I come from an NGO background, and I can tell you with confidence that one of the strongest ways to raise funds is human interest stories and case studies. However, I think the best place for them is not on the website itself. It is good to have them on the forums that we will build at a later phase of this project. 

It might also be worth considering a demo for this project's initial launch, or at some point in the future. Where a 2-min promotional video might highlight some stories from patients as well.

As for bugs, rest assured we are working around the clock to make sure we give you the best possible quality. I am very confident in the team's capacity, and I continue to test the features even after they become part of the code base. We will be sure to build something you're proud to use and present.

As I mentioned today, no later than Monday, we will provide you with a live website where you can link the user agreement, and even surf around the different views and pages of the website if you'd like. We would welcome any feedback about how you find the experience then.

**Comment by FarahZaqout** [comment]
Hey, @db626.

I'm sorry to say that yesterday was the start for full stack planning. As a result, we had to put the work on views on hold. 

We will not be able to give you a live address today unfortunately. However, work on the views is very close to complete. We are resuming the work on them right now.

**Comment by FarahZaqout** [comment]
Progress is going smoothly, and we expect to finalize the initial views from figma by tomorrow.
Sorry about the delay.
